version: "3.8"
services:
  ui:
    container_name: minesweeper-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: minesweeper-ui:lts
    ports:
      - "8080:8080"
    volumes:
      - ./ui:/app/ui
    env_file: .env.development

  db:
    container_name: minesweeper-db
    build:
      context: ./db
      dockerfile: Dockerfile
    image: minesweeper-db:lts
    ports:
      - "27018:27017"
    volumes:
      - ./db/config.js:/docker-entrypoint-initdb.d/config.js
    env_file: .env.development
    environment:
      MONGO_INITDB_DATABASE: minesweeper

  api:
    container_name: minesweeper-api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: minesweeper-api:lts
    ports:
      - "5002:5002"
    volumes:
      - ./api:/app/api
    env_file: .env.development
